### ISSUE TITLE
GitLab update failing: how to fix it

### ISSUE THREAD

**Issue by EpocDotFr** [scaleway-community/scaleway-gitlab#10]
I had troubles when updating GitLab from the `apt` repository (`apt-get install gitlab-ci`) that is already created when spawning the C1 instance. A folder used to backup the database was missing, so the update failed every time. To fix this problem:

    cd /var/opt/gitlab && mkdir backups && chown git backups

May be relevant to create this directory when installing the GitLab C1 image.

**Comment by moul** [comment]
@EpocDotFr thanks for reporting, the PR #11 should ensure the directory exists
