### ISSUE TITLE
Why 150GB volume?

### ISSUE THREAD

**Issue by khromov** [scaleway-community/scaleway-gitlab#12]
Would be nice to have a 50 or even 100GB volume for smaller projects.

**Comment by moul** [comment]
We consider that this image needs 150G by default, but you can build your own one with 50G.

We plan to manage multiple size for an image in an evolution of our image hub.

**Comment by oviliz** [comment]
Do this had an evolution then? When trying to install from Scaleway shows 50 while I would like the opposite, using 150. :)

**Comment by QuentinPerez** [comment]
Hi @oviliz,
We have changed the size of images  to be able to boot on VC1S, if you want you can add volume with the control panel :)

**Comment by oviliz** [comment]
Hi @QuentinPerez , thanks for your reply. Yes, I know I could add volumes but I'm so annoyed to mount drives etc.

**Comment by QuentinPerez** [comment]
You can also make your own `scaleway-giltab` image (150GB) with our [image-builder](https://github.com/scaleway/image-builder)
To do that follow the instructions to craft your image, you need to change 50GB to 150GB in the Makefile.

**Comment by moul** [comment]
@oviliz, we recently switched all our images to a fixed size of 50GiB, you can add secondary volumes to complete your needs

We are working on a volume resize solution so you can boot on your wanted size while keeping only one volume, no ETA for now
