### ISSUE TITLE
How do you update GitLab-CE?

### ISSUE THREAD

**Issue by IWriteThings** [scaleway-community/scaleway-gitlab#16]
I used the scaleway-gitlab docker image to build and deploy a copy of GitLab. I then configured GitLab and am successfully using it. The system reports that my copy of GitLab is out of date. However, if you run

```
$ apt-get update
$ apt-get install gitlab-ce --dry-run
```

The system states that I am running the latest version of GitLab. For future reference, will the GitLab-CE repository be updated and will I be able to do a simple apt-get upgrade to stay up to date with the latest version? This is my first time using docker to build an image and I want to make sure that I will not need to do something outside the ordinary to stay up to date.

**Comment by EpocDotFr** [comment]
GitLab latest build is always late on apt. Don't worry, you have the latest version but the apt repository is not up to date.

**Comment by IWriteThings** [comment]
Thanks a bunch!

**Comment by EpocDotFr** [comment]
The Gitlab CE binaries repository that Scaleway uses for their servers is https://packages.gitlab.com/gitlab/raspberry-pi2, which seems to be up to date. But updating Gitlab CE with your command (as I always did) doesn't seem to work anymore: no updates are found.

**Comment by EpocDotFr** [comment]
@moul I think this issue should be reopened and investigated, there is something strange happening here

**Comment by mekanics** [comment]
There is no version for debian higher than 8.5.0 in the package list. All the newer version are for raspbian. see https://packages.gitlab.com/gitlab/raspberry-pi2?filter=debs

you could change the distribution in the following file: (Do not ask me if that's a good idea or not. In case of doubt, it is not.) 
`/etc/apt/sources.list.d/gitlab_raspberry-pi2.list`

from 

```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/raspberry-pi2

deb https://packages.gitlab.com/gitlab/raspberry-pi2/debian/ jessie main
deb-src https://packages.gitlab.com/gitlab/raspberry-pi2/debian/ jessie main
```

to

```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/raspberry-pi2

deb https://packages.gitlab.com/gitlab/raspberry-pi2/raspbian/ jessie main
deb-src https://packages.gitlab.com/gitlab/raspberry-pi2/raspbian/ jessie main
```
  
  
should we create an issue for gitlab, so they continue to deploy for debian?

**Comment by mekanics** [comment]
aaaand here ist the issue I just opened: https://gitlab.com/gitlab-org/gitlab-ce/issues/15184

**Comment by moul** [comment]
@mekanics, thank you for this comment,

We will wait the answer from the GitLab team and switch to the raspbian repo if they prefer to deprecate the debian's one

**Comment by IWriteThings** [comment]
Will this new predicament require me to rebuild my image later?

**Comment by EpocDotFr** [comment]
The Gitlab staff just responded. It seems that we can safely change our source lists.

**Comment by EpocDotFr** [comment]
I just modified my Gitlab source file on my Gitlab Scaleway instance. It works very well when I do `apt-get update && apt-get upgrade` (updates are found) but :warning: **beware** of the Scaleway image you are using. 

I'm using the old, Debian Wheezie based image, so I just have to change the `https://packages.gitlab.com/gitlab/raspberry-pi2/debian/` URL to `https://packages.gitlab.com/gitlab/raspberry-pi2/raspbian/` **without** changing the Debian version (`wheezie`).

**Comment by moul** [comment]
@EpocDotFr ok perfect, do you want to do this tiny PR ?

You don't need to run the whole build platform, just edit the file from GitHub or from your command line.

**Comment by EpocDotFr** [comment]
@IWriteThings Nope (tested :wink:)

@mekanics Do you want to do this PR? You discovered the source :smile:

**Comment by EpocDotFr** [comment]
@IWriteThings Nope (tested :wink:)

@moul There is no need to make a PR because in the current Scaleway image version the new URL will be used automatically (via the `https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh` script). Correct me if I'm wrong ^^

**Comment by mekanics** [comment]
@EpocDotFr : I think you're wrong :) If you run this script, it will create `/etc/apt/sources.list.d/gitlab_gitlab-ce.list` which is for amd64. And it will still use the debian instead of the raspbian distribution.

so yes, we need a PR ;)

**Comment by EpocDotFr** [comment]
Seems that the `raspberry-pi2/raspbian` packages are no more updated since months. LAtest was https://packages.gitlab.com/gitlab/raspberry-pi2/packages/raspbian/wheezy/gitlab-ce_8.10.0+20160708164941-rc3.ce.0_armhf.deb.

**Comment by mekanics** [comment]
raspbian is not being updated anymore. We should go back to the debian packages. 
I already did open an issue for this #28

**Comment by EpocDotFr** [comment]
Thank you! I wasn't aware about this.
