### ISSUE TITLE
Web interface isn't deployed correctly on C2M server

### ISSUE THREAD

**Issue by khanon** [scaleway-community/scaleway-gitlab#20]
Hello,

When I launch a Gitlab image on C2M server, the public IP link to its web interface crashes, with a parse error for XML data.

**Comment by khanon** [comment]
Just saw the "**This image is meant to be used on a C1 server**." my bad

**Comment by moul** [comment]
Actually it should works on C2M too, I will investigate, sorry the x86_64 image is pretty new :)

**Comment by moul** [comment]
I started an attempt to fix the issue on x86_64 servers (#21), @QuentinPerez can you help me to finish the job ?

**Comment by QuentinPerez** [comment]
Hi @khanon,

We have released a new version which works also on C2*
Ping me if you have any trouble. 😊

**Comment by QuentinPerez** [comment]
I close this issue, do not hesitate to reopen it
