### ISSUE TITLE
Gitlab is not able to send emails

### ISSUE THREAD

**Issue by mekanics** [scaleway-community/scaleway-gitlab#25]
I did configure gitlab to send emails per smtp. 

```yml
# /etc/gitlab/gitlab.rb
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.mandrillapp.com"
gitlab_rails['smtp_port'] = 587
gitlab_rails['smtp_user_name'] = [MY_USERNAME]
gitlab_rails['smtp_password'] = [MY_API_KEY]
gitlab_rails['smtp_domain'] = [MY_DOMAIN]
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
```

I did deactivate ipv6, to be sure it's not a misconfiguration. 
Anyway it's a C1 instance. Why is ipv6 activated? Since when is ipv6 available on a C1?

Sidekiq gives me this error: `Net::OpenTimeout: execution expired`

I tried to connect with telnet... It's not working either
```shell
$ telnet smtp.mandrillapp.com 587
telnet: Unable to connect to remote host: Connection timed out
```
What am I missing?

**Comment by moul** [comment]
Did you configure the security groups of your server?

https://www.scaleway.com/faq/server/#-I-cannot-send-any-email

**Comment by mekanics** [comment]
😅 Ok I don't know what to say. 

let's close this issue and never talk about it ever again. 😬 

thank!

**Comment by moul** [comment]
:) no problem

**Comment by brylie** [comment]
I am having the same problem. I have configured my default security group to allow SMTP and rebooted the server. I still cannot telnet to a server using port 465 or 587.

The link to the FAQ item above gives a 404. What else should I try to troubleshoot this problem?

**Comment by brylie** [comment]
Simply rebooting from SSH did not work. My solution was to shut down the server from the scaleway panel and start it up again.
