### ISSUE TITLE
use the debian src instead of raspbian

### ISSUE THREAD

**Issue by mekanics** [scaleway-community/scaleway-gitlab#28]
looks like gitlab changed the src from raspbian back to debian. (see v8.10 https://packages.gitlab.com/gitlab/raspberry-pi2) 

so I think we should revert the PR #24 we made a few months ago. 

and for the current installations, here is the command to use: 
`sed -i 's/raspbian/debian/g' /etc/apt/sources.list.d/gitlab_raspberry-pi2.list`

**Comment by EpocDotFr** [comment]
I personally had to edit the `/etc/apt/sources.list.d/gitlab_ce.list` file. And then `apt-get update && apt-get upgrade` and then :ok_hand:

**Comment by moul** [comment]
Nice, would you like to open a Pull-Request ?
