### ISSUE TITLE
550 Access denied - Invalid HELO name

### ISSUE THREAD

**Issue by moul** [scaleway-community/scaleway-gitlab#7]
Continuing discussion from https://github.com/scaleway/image-ubuntu/issues/31#issuecomment-140135273 from @GeGeek

> Hi,
> i was getting this error when i tried to send an email to fully qualifed domain name, and not with free email services like hotmail, gmail etc..
> So i fixed that by editing the file main.cf in /etc/postfix/
> I changed the value for "myhostname = ", the default value was something like B84665785255..
> Could you fix it in the next release please ?
> Thanks !

---

> i have installed Gitlab, and no email were sent, so i asked why to support, and they told me that:

>> I have been looking into your issue, we are going to fix this very soon.
scaleway-community/scaleway-gitlab#6
>> In the mean time, you should be able to send mail by running:
>> 'dpkg-reconfigure postfix'

> I installed postfix and i noticed that no mail log file was installed in my server, so the support told me that:
>> The default configuration of the postfix server is to put logs in /var/log/syslog.
>>  Unfortunately, the latest build of your image has his syslog broken, you need to run 'chown root:syslog /var/log' to fix it.
>> https://github.com/scaleway/image-ubuntu/pull/22

> After that emails was working, but not correctly, and in log files i was able to see "invalid hello name...
> So i found the solution and the support told me to report this issue here !

**Comment by moul** [comment]
No luck, you just encountered 2 recent problems :)

For the `/var/log`, this is fixed in the Ubuntu and Debian images for < 1 hour (https://github.com/scaleway/image-ubuntu/pull/30) :) we now need to rebuild the GitLab image that depends on Ubuntu Trusty to get this working without hotfix

About the mail issue, I think it was fixed with scaleway-community/scaleway-gitlab#6, @edouardb, can you confirm ?

When I have the confirmation the mail issue is fixed, I will rebuild and deploy a new version of the GitLab image with the two fixes

Thanks

**Comment by GeGeek** [comment]
Hi is this deployed now ?

Thanks

**Comment by moul** [comment]
Hi @GeGeek, nop we were fixing other issues in the Ubuntu image (inherited from GitLab), we will batch release new versions today or tomorrow

For now you should be able to hotfix the image by calling `dpkg-reconfigure postfix`

**Comment by moul** [comment]
Done the image is now released
