### ISSUE TITLE
Change the root URL of GitLab

### ISSUE THREAD

**Issue by EpocDotFr** [scaleway-community/scaleway-gitlab#8]
I spawned a brand new C1 server with a Gitlab image and a public IP. I assigned this IP to a subdomain I own (`git.example.com` DNS A record), but certain URLs are unexpectly looking like `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX.pub.cloud.scaleway.com`.

I've seen this in the avatars path (both groups and projects), and in the clone URLs (both SSH and HTTP). These URLs requires to login to Gitlab because they are different compared to the URL I use to access the Gitlab instance.

How can I change the root path of Gitlab to `git.example.com` to fix this problem?

**Comment by EpocDotFr** [comment]
I found this in the Gitlab doc wich may help: http://doc.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab :)

**Comment by edouardb** [comment]
Hello,

You can change the external url by editing the `external_url` entry in `/etc/gitlab/gitlab.rb`.
Then execute the following commands to reload your configuration:

```
gitlab-ctl reconfigure &> /dev/null
gitlab-ctl reconfigure &> /dev/null
```

**Comment by EpocDotFr** [comment]
Thanks, will test this ASAP and go back to you :)

**Comment by EpocDotFr** [comment]
PS: the commands bellow are the same :)

**Comment by edouardb** [comment]
I know but there is an issue with `gitlab-ctl reconfigure ` so you need to run it twice :smile:

**Comment by edouardb** [comment]
Did it work?

**Comment by EpocDotFr** [comment]
I didn't tried yet, I'll notice you when it's done ^^

**Comment by EpocDotFr** [comment]
It works well, thanks. After running these commands, some minutes are necessary to apply the new configuration.

Maybe mention all these tricks in the image doc should help other users :)

**Comment by noeticgears** [comment]
thanks, I'm facing the same issue, I'll give a try

**Comment by noeticgears** [comment]
it wroked as expected
