### ISSUE TITLE
Properly update GitLab

### ISSUE THREAD

**Issue by EpocDotFr** [scaleway-community/scaleway-gitlab#9]
GitLab 8.1 was released a few days ago, however I spawned my C1 instance before this release. How to properly update GitLab on a GitLab C1 image ? Is this possible ? Is this recommendable ?

**Comment by edouardb** [comment]
Yes it is possible, you have to follow instruction in the official GitLab documentation https://about.gitlab.com/downloads/#raspberrypi2
